// Seed data for initial recipes
export const initialRecipes = [
    { title: "Creamy Matcha Pasta", type: "cooking", image: "/recipes/creamymatchapasta.jpg" },
    { title: "Matcha Risotto", type: "cooking", image: "/recipes/risotto.jpg" },
    { title: "Ochazuke", type: "cooking", image: "/recipes/ochazuke.jpg" },
    { title: "Matcha Chawanmushi", type: "cooking", image: "/recipes/chawanmushi.webp" },
    { title: "Matcha Onigiri", type: "cooking", image: "/recipes/onigiri.jpg" },
    { title: "Matcha Gyoza", type: "cooking", image: "/recipes/gyoza.jpeg" },
    { title: "Matcha Soba Noodles", type: "cooking", image: "/recipes/noodles.avif" },
    { title: "Iced Matcha Espresso", type: "drink", image: "/recipes/icedmatchaespresso.jpg" },
    { title: "Koicha (Thick Matcha)", type: "drink", image: "/recipes/koicha.jpg" },
    { title: "Usucha (Thin Matcha)", type: "drink", image: "/recipes/usucha.jpeg" },
    { title: "Matcha Rose Latte", type: "drink", image: "/recipes/matcharoselatte.jpg" },
    { title: "Coconut Matcha Drink", type: "drink", image: "/recipes/coconutmatcha.webp" },
    { title: "Matcha Yuzu Sparkler", type: "drink", image: "/recipes/matchayuzu.jpg" },
    { title: "Matcha Basque Cheesecake", type: "dessert", image: "/recipes/cheesecake.jpg" },
    { title: "Matcha Tiramisu", type: "dessert", image: "/recipes/tiramisu.jpg" },
    { title: "Matcha Brownies", type: "dessert", image: "/recipes/matchabrownies.jpg" },
    { title: "Matcha White Choc Cookies", type: "dessert", image: "/recipes/matchacookies.jpg" },
    { title: "Matcha Panna Cotta", type: "dessert", image: "/recipes/panacottamatcha.jpg" },
    { title: "Matcha Affogato", type: "dessert", image: "/recipes/affogato.jpg" },
    { title: "Matcha Lava Cake", type: "dessert", image: "/recipes/matchalava.jpg" },
    { title: "Nama Matcha Chocolate", type: "dessert", image: "/recipes/namematcha.jpg" },
    { title: "Matcha Macarons", type: "dessert", image: "/recipes/magarongmatcha.jpg" },
    { title: "Matcha Chocolate Cups", type: "dessert", image: "/recipes/chocolatcups.jpg" },
    { title: "Matcha Chocolate Balls", type: "dessert", image: "/recipes/matchachocolateball.webp" },
    { title: "Matcha Pound Cake", type: "dessert", image: "/recipes/poundcake.avif" },
    { title: "Matcha White Chocolate Bark", type: "dessert", image: "/recipes/whitechoc.png" },
];
